definitions:
  api.ErrorResponse:
    properties:
      error:
        type: string
      message:
        type: string
    type: object
  models.Packet:
    properties:
      destination_ip:
        type: string
      flags:
        type: string
      id:
        type: string
      payload:
        type: string
      port:
        maximum: 65535
        minimum: 1
        type: integer
      protocol:
        enum:
        - TCP
        - UDP
        - ICMP
        - HTTP
        - HTTPS
        type: string
      size:
        minimum: 1
        type: integer
      source_ip:
        type: string
      timestamp:
        type: string
      ttl:
        type: integer
    required:
    - destination_ip
    - id
    - protocol
    - source_ip
    - timestamp
    type: object
  models.PacketResponse:
    properties:
      packets:
        items:
          $ref: '#/definitions/models.Packet'
        type: array
      timestamp:
        type: string
      total:
        type: integer
    type: object
info:
  contact: {}
paths:
  /packets:
    get:
      consumes:
      - application/json
      description: Retrieve all sniffed packets with optional filtering
      parameters:
      - description: Filter by protocol (TCP, UDP, HTTP, HTTPS)
        in: query
        name: protocol
        type: string
      - description: Filter by source IP address
        in: query
        name: source_ip
        type: string
      - description: Filter by destination IP address
        in: query
        name: destination_ip
        type: string
      - description: 'Limit number of results (default: no limit)'
        in: query
        name: limit
        type: integer
      - description: 'Offset for pagination (default: 0)'
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: List of packets
          schema:
            $ref: '#/definitions/models.PacketResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Get all packets
      tags:
      - packets
swagger: "2.0"
